#!/usr/bin/env sh

PYTHON_VERSION=$(python3 -c 'import sys; print("{}.{}".format(*sys.version_info))')

sip-install \
    --qt-shared \
    --concatenate 1 \
    --confirm-license \
    --debug \
    --verbose \
    --jobs="${FLATPAK_BUILDER_N_JOBS}" \
    --build-dir="${FLATPAK_BUILDER_BUILDDIR}/tmp" \
    --target-dir="${FLATPAK_DEST}/lib/python${PYTHON_VERSION}/site-packages" \
    --enable=QtCore \
    --enable=QtDBus \
    --enable=QtGui \
    --enable=QtMultimedia \
    --enable=QtNetwork \
    --enable=QtWidgets \
    --no-dbus-python \
    --no-designer-plugin \
    --no-docstrings \
    --no-qml-plugin \
    --no-tools \
    --qmake-setting QMAKE_CFLAGS="$CFLAGS" \
    --qmake-setting QMAKE_CXXFLAGS="$CXXFLAGS" \
    --qmake-setting QMAKE_LFLAGS="$LDFLAGS"
