#!/bin/sh

${PYTHON} configure.py \
    --assume-shared \
    --concatenate \
    --confirm-license \
    --enable=QtCore \
    --enable=QtGui \
    --enable=QtNetwork \
    --enable=QtWidgets \
    --no-designer-plugin \
    --no-dist-info \
    --no-docstrings \
    --no-qml-plugin \
    --no-qsci-api \
    --no-sip-files \
    --no-stubs \
    --no-tools \
    --sysroot=/app
