#!/bin/sh


PYTHON=python2
PYTHON_VERSION=$(${PYTHON} -c 'import sys; print(sys.version[:3])')


${PYTHON} configure.py \
    --confirm-license \
    --enable=QtCore \
    --enable=QtGui \
    --enable=QtNetwork \
    --no-designer-plugin \
    --no-docstrings \
    --no-qsci-api \
    --bindir=/app/bin \
    --destdir=/app/lib/python${PYTHON_VERSION}/site-packages \
    --sipdir=/app/share/sip
