#!/bin/sh

PYTHON_VERSION=$(${PYTHON} -c 'import sys; print(sys.version[:3])')

${PYTHON} configure.py \
    --assume-shared \
    --concatenate \
    --confirm-license \
    --destdir=/app/lib/python${PYTHON_VERSION}/site-packages \
    --enable=QtCore \
    --enable=QtGui \
    --enable=QtMultimedia \
    --enable=QtNetwork \
    --enable=QtWidgets \
    --no-designer-plugin \
    --no-dist-info \
    --no-docstrings \
    --no-qml-plugin \
    --no-qsci-api \
    --no-sip-files \
    --no-stubs \
    --no-tools \
    QMAKE_CFLAGS_RELEASE="$CFLAGS" \
    QMAKE_CXXFLAGS_RELEASE="$CXXFLAGS" \
    QMAKE_LFLAGS_RELEASE="$LDFLAGS"
