#!/bin/sh

PYTHON_VERSION=$(${PYTHON} -c 'import sys; print(sys.version[:3])')

sip-install \
    --verbose \
    --build-dir=${FLATPAK_BUILDER_BUILDDIR}/tmp \
    --target-dir=${FLATPAK_DEST}/lib/python${PYTHON_VERSION}/site-packages \
    --enable=QtCore \
    --enable=QtGui \
    --enable=QtMultimedia \
    --enable=QtNetwork \
    --enable=QtWidgets \
    --confirm-license \
    --qt-shared \
    --no-designer-plugin \
    --no-qml-plugin \
    --no-dbus-python \
    --no-tools \
    --concatenate 1 \
    --debug \
    --no-docstrings
