#!/bin/sh


PYTHON=python2
PYTHON_VERSION=$(${PYTHON} -c 'import sys; print(sys.version[:3])')


${PYTHON} configure.py \
    --bindir=/app/bin \
    --destdir=/app/lib/python${PYTHON_VERSION}/site-packages \
    --incdir=/app/include \
    --pyidir=/app/lib/python${PYTHON_VERSION}/site-packages \
    --sipdir=/app/share/sip
